#! /usr/bin/python

#
#   File:       Test.py
#
#   Contains:   A test script for the FSMegaInfo program.
#
#   Written by: DTS
#
#   Copyright:  Copyright (c) 2008 Apple Inc. All Rights Reserved.
#
#   Disclaimer: IMPORTANT: This Apple software is supplied to you by Apple Inc.
#               ("Apple") in consideration of your agreement to the following
#               terms, and your use, installation, modification or
#               redistribution of this Apple software constitutes acceptance of
#               these terms.  If you do not agree with these terms, please do
#               not use, install, modify or redistribute this Apple software.
#
#               In consideration of your agreement to abide by the following
#               terms, and subject to these terms, Apple grants you a personal,
#               non-exclusive license, under Apple's copyrights in this
#               original Apple software (the "Apple Software"), to use,
#               reproduce, modify and redistribute the Apple Software, with or
#               without modifications, in source and/or binary forms; provided
#               that if you redistribute the Apple Software in its entirety and
#               without modifications, you must retain this notice and the
#               following text and disclaimers in all such redistributions of
#               the Apple Software. Neither the name, trademarks, service marks
#               or logos of Apple Inc. may be used to endorse or promote
#               products derived from the Apple Software without specific prior
#               written permission from Apple.  Except as expressly stated in
#               this notice, no other rights or licenses, express or implied,
#               are granted by Apple herein, including but not limited to any
#               patent rights that may be infringed by your derivative works or
#               by other works in which the Apple Software may be incorporated.
#
#               The Apple Software is provided by Apple on an "AS IS" basis. 
#               APPLE MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING
#               WITHOUT LIMITATION THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
#               MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, REGARDING
#               THE APPLE SOFTWARE OR ITS USE AND OPERATION ALONE OR IN
#               COMBINATION WITH YOUR PRODUCTS.
#
#               IN NO EVENT SHALL APPLE BE LIABLE FOR ANY SPECIAL, INDIRECT,
#               INCIDENTAL OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#               TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#               DATA, OR PROFITS; OR BUSINESS INTERRUPTION) ARISING IN ANY WAY
#               OUT OF THE USE, REPRODUCTION, MODIFICATION AND/OR DISTRIBUTION
#               OF THE APPLE SOFTWARE, HOWEVER CAUSED AND WHETHER UNDER THEORY
#               OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR
#               OTHERWISE, EVEN IF APPLE HAS BEEN ADVISED OF THE POSSIBILITY OF
#               SUCH DAMAGE.
#

import sys
import re
import os
import getopt
import struct

gDebug = 0

gNativeArch = None

# The subprocess module is part of Python 2.5, which isn't installed by default 
# on 10.4.  So if I can't import subprocess I implement runTool using popen2. 
# This is less than ideal because popen2 is just not as nice as subprocess. 
# Specifically, there's no easy way to read both stdout and stderr simultaneously, 
# which is necessary to avoid pipe deadlocks.

try:
    import subprocess

    def runTool(args):
        if gDebug >= 1:
            print >> sys.stderr, args
        s = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        resultOut, resultErr = s.communicate()
        result = (s.wait(), resultOut, resultErr)
        if gDebug >= 2:
            print result
        return result

except:
    import popen2
    
    def runTool(args):
        if gDebug >= 1:
            print >> sys.stderr, args
        child = popen2.Popen3(args, capturestderr=True)
        
        # This is /so/ bodgy.  We really need to read both stdout and stderr 
        # until both of them hit EOF, but that's hard to do.  This code works 
        # well enough for my specific needs, but don't even /think/ about 
        # reordering the next two lines!
        
        resultOut = child.fromchild.read()
        resultErr = child.childerr.read()
        result = (child.wait(), resultOut, resultErr)
        if gDebug >= 2:
            print result
        return result

def runFSMegaInfo(args, arch=""):
    if arch == "":
        result = runTool(["build/Debug/FSMegaInfo"] + list(args))
    else:
        result = runTool(["arch", "-" + arch, "build/Debug/FSMegaInfo"] + list(args))
    return result

def fixStatFS(results, arch):
    if arch == "i386" or arch == "ppc":
        results = (results[0], re.sub("f_flags       = 0x", "f_flags       = 0x00000000", results[1]), results[2])
    return results

def fixTellDir(results, arch):
    return (results[0], re.sub("telldir   = [0-9]+", "telldir   = xxx", results[1]), results[2])

def fixFTSPointers(results, arch):
    tmp = re.sub("(fts_statp +|fts_accpath +|fts_path +)= 0x[0-9a-f]+", "\\1= 0xxxx", results[1])

    tmp = re.sub("fts_cycle   = 0x[0-9a-f]+", "fts_cycle   = 0xxxx", tmp)
    
    return (results[0], tmp, results[2])

def fixVolumeDates(results, arch):
    # FSGetVolumeInfo returns bogus results for the createDate and checkedDate 
    # in 64-bit code <rdar://problem/5740217>, so we just ignore those fields 
    # in our test.
    #
    # I also nix the modifyDate because, when you have an AFP server mounted, 
    # things can differ slightly in 64-bit vs 32-bit.

    tmp = re.sub("(createDate +|checkedDate +|modifyDate +)= [0-9]+\\.[0-9]+\\.[0-9]+ \\([a-zA-Z0-9 :,\\+]+\\)", "\\1= xxx", results[1])

    return (results[0], tmp, results[2])

def fixVolParmsPointers(results, arch):
    return (results[0], re.sub("vMDeviceID           = 0x[0-9a-f]+", "vMDeviceID           = 0xxxx", results[1]), results[2])
    
def fixCatInfoPermissions(results, arch):
    # The last 4 bytes (8 bytes in the 64-bit case) of the permissions are a pointer, 
    # which we want to remove.
    return (results[0], re.sub("permissions      = (?P<first>([0-9a-f][0-9a-f] ){12})([0-9a-f][0-9a-f] ){4}(\\n +(?P<third>([0-9a-f][0-9a-f] ){4}))?", "permissions      = \\g<first>", results[1]), results[2])
    
def fixFileSecOwner(results, arch):
    # For some reason the fsec_owner and fsec_group fields are coming back 
    # different on i386 and x86_64.  Neither of them looks particularly 
    # valid.  I'm going to ignore this for the moment because I'm out of time.
    return (results[0], re.sub("(fsec_owner|fsec_group) = .*", "\\1 = xxx", results[1]), results[2])

def fixAliasVolumeCreateDate(results, arch):
    return (results[0], re.sub("volumeCreateDate           = .*\n", "", results[1]), results[2])

def byteSwapValue(text, fieldName, fmt):
    def swapper(m):
        swappedValue = struct.unpack(">" + fmt, struct.pack("<" + fmt, long(m.group('value'))))[0]
        return m.group('prefix') + str(swappedValue)
    return re.sub("(?P<prefix>" + fieldName + " += )(?P<value>[0-9]+)", swapper, text)
    
def byteSwapValueHex(text, fieldName, fmt):
    def swapper(m):
        swappedValue = struct.unpack(">" + fmt, struct.pack("<" + fmt, long(m.group('value'), 16)))[0]
        if fmt == "q":
            outFmt = "%016x"
        else:
            outFmt = "%08x"
        return ("%s0x" + outFmt) % (m.group('prefix'), swappedValue)
    return re.sub("(?P<prefix>" + fieldName + " += )(?P<value>0x[0-9]+)", swapper, text)
    
def fixRosettaIDs(results, arch):
    # Necessary to work around <rdar://problem/5745429>.
    if arch == "ppc" and gNativeArch == "i386":
        output = results[1]

        output = byteSwapValue(output, "ATTR_CMN_FILEID", "Q")
        output = byteSwapValue(output, "ATTR_CMN_PARENTID", "Q")
        output = byteSwapValue(output, "ATTR_DIR_LINKCOUNT", "I")
        output = byteSwapValue(output, "ATTR_DIR_ENTRYCOUNT", "I")
        output = byteSwapValueHex(output, "ATTR_DIR_MOUNTSTATUS", "I")
        
        output = re.sub("DIR_MNTSTATUS_MNTPOINT = NO\n        ... and others \\(0x1000000\\)", "DIR_MNTSTATUS_MNTPOINT = YES", output)
        
        results = (results[0], output, results[2])
    return results

def printResultsSideBySide(columnWidth, left, right):
    if left != '' and right != '':
        left  = left.splitlines()
        right = right.splitlines()
        for lineIndex in xrange(0, max(len(left), len(right))):
            if lineIndex < len(left):
                l1 = left[lineIndex]
            else:
                l1 = ""
            if lineIndex < len(right):
                l2 = right[lineIndex]
            else:
                l2 = ""
            if l1 == l2:
                mark = " "
            else:
                mark = "!"
            print >> sys.stderr, "%-*s %s %s" % (columnWidth, l1[:columnWidth], mark, l2[:columnWidth])
    
def compareResultsForArchitectures(archList):
    # stty will fail when running on 10.4 because my subprocess compatibility 
    # code, which Popen3, sets stdin to be a pipe, not be the tty device.  
    # This isn't a big deal so I'm just going to ignore the erorr here.
    try:
        numberOfColumns = int(runTool(['stty', 'size'])[1].split()[1])
    except:
        print >> sys.stderr, "*** stty failed; using a default value for the number of columns"
        numberOfColumns = 80
    columnWidth = (numberOfColumns - 5) / 2

    regressionTest = True
    
    commands = []
    if regressionTest:
        commands += [
            (('stat', '/'), ()),
            (('lstat', '/'), ()),
            (('stat', '/mach_kernel'), ()),
            (('lstat', '/mach_kernel'), ()),
    
            (('-v', 'stat', '/'), ()),
            (('-v', 'lstat', '/'), ()),
            (('-v', 'stat', '/mach_kernel'), ()),
            (('-v', 'lstat', '/mach_kernel'), ()),
    
            (('statfs', '/'), (fixStatFS,)),
            (('lstatfs', '/'), (fixStatFS,)),
            (('statfs', '/mach_kernel'), (fixStatFS,)),
            (('lstatfs', '/mach_kernel'), (fixStatFS,)),
    
            (('-v', 'statfs', '/'), (fixStatFS,)),
            (('-v', 'lstatfs', '/'), (fixStatFS,)),
            (('-v', 'statfs', '/mach_kernel'), (fixStatFS,)),
            (('-v', 'lstatfs', '/mach_kernel'), (fixStatFS,)),
    
            (('getfsstat',), (fixStatFS,)),
            (('getfsstat', '-r'), (fixStatFS,)),
    
            (('-v', 'getfsstat',), (fixStatFS,)),
            (('-v', 'getfsstat', '-r'), (fixStatFS,)),
    
            (('-vv', 'getfsstat',), (fixStatFS,)),
            (('-vv', 'getfsstat', '-r'), (fixStatFS,)),
        ]

    if regressionTest:
        commands += [
            (('getdirentries', '/System/Library/CoreServices/'), ()),
            (('getdirentries', '-bufSize', '10240', '/System/Library/CoreServices/'), ()),
            (('getdirentries', '-r', '/System/Library/CoreServices/'), ()),
    
            (('-v', 'getdirentries', '/System/Library/CoreServices/'), ()),
            (('-v', 'getdirentries', '-bufSize', '10240', '/System/Library/CoreServices/'), ()),
            (('-v', 'getdirentries', '-r', '/System/Library/CoreServices/'), ()),
    
            (('readdir', '/System/Library/CoreServices/'), ()),
            (('readdir', '-r', '/System/Library/CoreServices/'), ()),
    
            (('-v', 'readdir', '/System/Library/CoreServices/'), (fixTellDir,)),
            (('-v', 'readdir', '-r', '/System/Library/CoreServices/'), (fixTellDir,)),
    
            (('fts', '/System/Library/CoreServices/Finder.app'), (fixFTSPointers,)),
            # fts has a bunch of options arguments but I can't be bothered exercising those cases.
        ]

    if regressionTest:
        commands += [
            (('listxattr', '/System/Library/CoreServices/Finder'), ()),
            (('listxattr', '-bufSize', '10240', '/System/Library/CoreServices/Finder'), ()),
    
            (('getxattr', '/System/Library/CoreServices/Finder', 'com.apple.FinderInfo'), ()),
            (('getxattr', '/System/Library/CoreServices/Finder', 'com.apple.ResourceFork'), ()),
    
            (('-v', 'getxattr', '/System/Library/CoreServices/Finder', 'com.apple.FinderInfo'), ()),
            (('-v', 'getxattr', '/System/Library/CoreServices/Finder', 'com.apple.ResourceFork'), ()),
    
            (('-vv', 'getxattr', '/System/Library/CoreServices/Finder', 'com.apple.FinderInfo'), ()),
            (('-vv', 'getxattr', '/System/Library/CoreServices/Finder', 'com.apple.ResourceFork'), ()),
        ]

    # In the commented out cases below it seems to be that getattrlist is misbehaving. 
    # I seem to remember seeing this problem because but I don't have time to investigate 
    # right now.
    
    if regressionTest:
        commands += [
            (('getattrlist', '/'), ()),
            (('getattrlist', '-ATTR_CMN_NAME', '/'), ()),
            (('getattrlist', '-ATTR_CMN_NAME', '/mach_kernel'), ()),
            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/'), ()),
            (('getattrlist', '-ATTR_VOL_INFO,ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/'), ()),
            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/mach_kernel'), ()),
            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/System/Library/CoreServices/Finder'), ()),
            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID', '/'), (fixRosettaIDs,)),
            (('getattrlist', '-ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/'), ()),
            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
#            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
#            (('getattrlist', '-ATTR_VOL_INFO,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/'), (fixRosettaIDs,)),
            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), (fixRosettaIDs,)),
            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), (fixRosettaIDs,)),
            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/mach_kernel'), (fixRosettaIDs,)),
#            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/mach_kernel'), ()),
#            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/mach_kernel'), ()),
#            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
#            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/mach_kernel'), ()),

            (('-v', 'getattrlist', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME', '/mach_kernel'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_VOL_INFO,ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/mach_kernel'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/System/Library/CoreServices/Finder'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID', '/'), (fixRosettaIDs,)),
            (('-v', 'getattrlist', '-ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
#            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
#            (('-v', 'getattrlist', '-ATTR_VOL_INFO,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/'), (fixRosettaIDs,)),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), (fixRosettaIDs,)),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), (fixRosettaIDs,)),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/mach_kernel'), (fixRosettaIDs,)),
#            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/mach_kernel'), ()),
#            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/mach_kernel'), ()),
#            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
#            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/mach_kernel'), ()),

            (('-vv', 'getattrlist', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME', '/mach_kernel'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_VOL_INFO,ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/mach_kernel'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/System/Library/CoreServices/Finder'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID', '/'), (fixRosettaIDs,)),
            (('-vv', 'getattrlist', '-ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
#            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
#            (('-vv', 'getattrlist', '-ATTR_VOL_INFO,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/'), (fixRosettaIDs,)),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), (fixRosettaIDs,)),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), (fixRosettaIDs,)),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/mach_kernel'), (fixRosettaIDs,)),
#            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/mach_kernel'), ()),
#            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/mach_kernel'), ()),
#            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
#            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/mach_kernel'), ()),
        ]

    if regressionTest:
        commands += [
            (('DADiskCopyDescription', 'disk0'), ()),
        ]

    if regressionTest:                                                                              #*Rosetta
        commands += [
            (('FSGetVolumeInfo', '/'), (fixVolumeDates,)),
            (('FSGetVolumeInfo', 'all'), (fixVolumeDates,)),

            (('-v', 'FSGetVolumeInfo', '/'), (fixVolumeDates,)),
            (('-v', 'FSGetVolumeInfo', 'all'), (fixVolumeDates,)),

            (('FSGetVolumeParms', '/'), (fixVolParmsPointers,)),
            (('-v', 'FSGetVolumeParms', '/'), (fixVolParmsPointers,)),

            (('FSCopyDiskIDForVolume', '/'), (fixVolParmsPointers,)),
        ]

    # These tests require that you have an AFP server mounted.
    
    if regressionTest:
        if os.path.exists('/Volumes/Fluffy'):
            commands += [
                (('FSGetVolumeMountInfo', '/Volumes/Fluffy'), ()),
                (('-v', 'FSGetVolumeMountInfo', '/Volumes/Fluffy'), ()),
    
                (('FSCopyURLForVolume', '/Volumes/Fluffy'), ()),
            ]
        else:
            print >> sys.stderr, '*** Skipped network volume tests'
    
    if regressionTest:
        commands += [
            (('FSGetCatalogInfo', '/'), ()),
            (('FSGetCatalogInfo', '/mach_kernel'), ()),
            (('FSGetCatalogInfo', '/Applications'), ()),
            (('FSGetCatalogInfo', '/System/Library/CoreServices/Finder'), ()),

            (('FSGetCatalogInfo', '-parent', '/'), ()),                                             #*Rosetta
            (('FSGetCatalogInfo', '-parent', '/mach_kernel'), ()),                                  #*Rosetta
            (('FSGetCatalogInfo', '-parent', '/Applications'), ()),                                 #*Rosetta
            (('FSGetCatalogInfo', '-parent', '/System/Library/CoreServices/Finder'), ()),           #*Rosetta

            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/'), (fixCatInfoPermissions,)),       #*Rosetta
            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/mach_kernel'), (fixCatInfoPermissions,)),                                #*Rosetta
            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/Applications'), (fixCatInfoPermissions,)),                               #*Rosetta
            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/System/Library/CoreServices/Finder'), (fixCatInfoPermissions,)),         #*Rosetta

            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/'), ()),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/mach_kernel'), ()),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/Applications'), ()),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/System/Library/CoreServices/Finder'), ()),

            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/'), ()),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/mach_kernel'), ()),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/Applications'), ()),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/System/Library/CoreServices/Finder'), ()),

            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/'), (fixCatInfoPermissions, fixFileSecOwner)),                                    #*Rosetta
            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/mach_kernel'), (fixCatInfoPermissions, fixFileSecOwner)),                         #*Rosetta
            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/Applications'), (fixCatInfoPermissions, fixFileSecOwner)),                        #*Rosetta
            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/System/Library/CoreServices/Finder'), (fixCatInfoPermissions, fixFileSecOwner)),  #*Rosetta

            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/'), (fixFileSecOwner,)),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/mach_kernel'), (fixFileSecOwner,)),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/Applications'), (fixFileSecOwner,)),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/System/Library/CoreServices/Finder'), (fixFileSecOwner,)),

            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/'), (fixFileSecOwner,)),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/mach_kernel'), (fixFileSecOwner,)),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/Applications'), (fixFileSecOwner,)),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/System/Library/CoreServices/Finder'), (fixFileSecOwner,)),
        ]

    if regressionTest:
        commands += [
            (('FSGetCatalogInfoBulk', '/'), ()),
            (('FSGetCatalogInfoBulk', '/Applications'), ()),

            (('FSGetCatalogInfoBulk', '-refs', '/'), ()),                                                                                                       #*Rosetta
            (('FSGetCatalogInfoBulk', '-refs', '/Applications'), ()),                                                                                           #*Rosetta

            (('FSGetCatalogInfoBulk', '-count', '5', '/'), ()),
            (('FSGetCatalogInfoBulk', '-count', '5', '/Applications'), ()),

            (('FSGetCatalogInfoBulk', '-kFSCatInfoGettableInfo', '/'), (fixCatInfoPermissions,)),                                                               #*Rosetta
            (('FSGetCatalogInfoBulk', '-kFSCatInfoGettableInfo', '/Applications'), (fixCatInfoPermissions,)),                                                   #*Rosetta

            (('-v', 'FSGetCatalogInfoBulk', '-kFSCatInfoGettableInfo', '/'), (fixCatInfoPermissions,)),
            (('-v', 'FSGetCatalogInfoBulk', '-kFSCatInfoGettableInfo', '/Applications'), (fixCatInfoPermissions,)),

            (('-vv', 'FSGetCatalogInfoBulk', '-kFSCatInfoGettableInfo', '/'), (fixCatInfoPermissions,)),
            (('-vv', 'FSGetCatalogInfoBulk', '-kFSCatInfoGettableInfo', '/Applications'), (fixCatInfoPermissions,)),

            (('FSGetCatalogInfoBulk', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/'), (fixCatInfoPermissions, fixFileSecOwner)),                    #*Rosetta
            (('FSGetCatalogInfoBulk', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/Applications'), (fixCatInfoPermissions, fixFileSecOwner)),        #*Rosetta

            (('-v', 'FSGetCatalogInfoBulk', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('-v', 'FSGetCatalogInfoBulk', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/Applications'), (fixCatInfoPermissions, fixFileSecOwner)),

            (('-vv', 'FSGetCatalogInfoBulk', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('-vv', 'FSGetCatalogInfoBulk', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/Applications'), (fixCatInfoPermissions, fixFileSecOwner)),
        ]

    if regressionTest:
        commands += [
            (('FSFindFolder', 'kOnSystemDisk', 'temp'), ()),
            (('FSFindFolder', 'kOnAppropriateDisk', 'temp'), ()),
            (('FSFindFolder', 'kSystemDomain', 'temp'), ()),
            (('FSFindFolder', 'kLocalDomain', 'temp'), ()),
            (('FSFindFolder', 'kNetworkDomain', 'temp'), ()),
            (('FSFindFolder', 'kUserDomain', 'temp'), ()),
            (('FSFindFolder', '/', 'temp'), ()),

            (('FSFindFolder', 'kOnSystemDisk', 'dlib'), ()),
            (('FSFindFolder', 'kOnAppropriateDisk', 'dlib'), ()),
            (('FSFindFolder', 'kSystemDomain', 'dlib'), ()),
            (('FSFindFolder', 'kLocalDomain', 'dlib'), ()),
            (('FSFindFolder', 'kUserDomain', 'dlib'), ()),
            (('FSFindFolder', '/', 'dlib'), ()),

            (('FSFindFolder', 'kOnSystemDisk', '0x757469C4'), ()),
            (('FSFindFolder', 'kOnAppropriateDisk', '0x757469C4'), ()),
            (('FSFindFolder', 'kSystemDomain', '0x757469C4'), ()),
            (('FSFindFolder', 'kLocalDomain', '0x757469C4'), ()),
            (('FSFindFolder', 'kUserDomain', '0x757469C4'), ()),
            (('FSFindFolder', '/', '0x757469C4'), ()),
        ]

    if regressionTest:
        commands += [
            (('FSCopyAliasInfo', '/'), (fixAliasVolumeCreateDate,)),
            (('FSCopyAliasInfo', '/mach_kernel'), (fixAliasVolumeCreateDate,)),
            (('FSCopyAliasInfo', '/System/Library/CoreServices/Finder'), (fixAliasVolumeCreateDate,)),
        ]

    if regressionTest:
        commands += [
            (('pathconf', '_PC_LINK_MAX', '/'), ()),
            (('pathconf', '_PC_MAX_CANON', '/dev/ttys000'), ()),
            (('pathconf', '_PC_MAX_INPUT', '/dev/ttys000'), ()),
            (('pathconf', '_PC_NAME_MAX', '/'), ()),
            (('pathconf', '_PC_PATH_MAX', '/'), ()),
            (('pathconf', '_PC_PIPE_BUF', '/'), ()),
            (('pathconf', '_PC_CHOWN_RESTRICTED', '/'), ()),
            (('pathconf', '_PC_NO_TRUNC', '/'), ()),
            (('pathconf', '_PC_VDISABLE', '/dev/ttys000'), ()),
            (('pathconf', '_PC_NAME_CHARS_MAX', '/'), ()),
            (('pathconf', '_PC_CASE_SENSITIVE', '/'), ()),
            (('pathconf', '_PC_CASE_PRESERVING', '/'), ()),
            (('pathconf', '_PC_EXTENDED_SECURITY_NP', '/'), ()),
            (('pathconf', '_PC_AUTH_OPAQUE_NP', '/'), ()),
            (('pathconf', '_PC_2_SYMLINKS', '/'), ()),
            (('pathconf', '_PC_ALLOC_SIZE_MIN', '/'), ()),
            (('pathconf', '_PC_ASYNC_IO', '/'), ()),
            (('pathconf', '_PC_FILESIZEBITS', '/'), ()),
            (('pathconf', '_PC_PRIO_IO', '/'), ()),
            (('pathconf', '_PC_REC_INCR_XFER_SIZE', '/'), ()),
            (('pathconf', '_PC_REC_MAX_XFER_SIZE', '/'), ()),
            (('pathconf', '_PC_REC_MIN_XFER_SIZE', '/'), ()),
            (('pathconf', '_PC_REC_XFER_ALIGN', '/'), ()),
            (('pathconf', '_PC_SYMLINK_MAX', '/'), ()),
            (('pathconf', '_PC_SYNC_IO', '/'), ()),
        ]
        
    for command in commands:
        canonicalResults = runFSMegaInfo(command[0], archList[0])
        for fix in command[1]:
            canonicalResults = fix(canonicalResults, archList[0])
            
        for arch in archList[1:]:
            results = runFSMegaInfo(command[0], arch)
            for fix in command[1]:
                results = fix(results, arch)
            if gDebug >= 2 or results != canonicalResults:
                if results != canonicalResults:
                    print >> sys.stderr, "*** Test failure"
                else:
                    print >> sys.stderr, "*** Debug output"
            
                print >> sys.stderr, "compareResultsForArchitectures"
                print >> sys.stderr, "args: %s" % str(command[0])
                print >> sys.stderr, "%-*s   %s" % (columnWidth, "canonical", "returned")
                print >> sys.stderr, "%-*s   %s" % (columnWidth, archList[0], arch)
                if canonicalResults[0] == results[0]:
                    mark = " "
                else:
                    mark = "!"
                print >> sys.stderr, "%-*d %s %d" % (columnWidth, canonicalResults[0], mark, results[0])
            
                print >> sys.stderr, "---"
                printResultsSideBySide(columnWidth, canonicalResults[1], results[1])        # stdout
                print >> sys.stderr, "---"
                printResultsSideBySide(columnWidth, canonicalResults[2], results[2])        # stderr
                print >> sys.stderr, "---"
            
                if results != canonicalResults:
                    sys.exit(1)

def runCrossArchitectureTest():
    if gNativeArch in ["x86_64", "i386"]:
        compareResultsForArchitectures(["x86_64", "i386"])
        #*Rosetta compareResultsForArchitectures(["x86_64", "ppc"])
    elif gNativeArch in ["ppc64", "ppc"]:
        compareResultsForArchitectures(["ppc64", "ppc"])
    else:
        print >> sys.stderr, "What architecture?"
        assert False

def generateFingerPrint(pathToTestVolume, arch):
    fullDump = True

    commands = []
    if fullDump:
        commands += [
            (('stat', '/'), ()),
            (('lstat', '/'), ()),
            (('stat', '/meg1'), ()),
            (('lstat', '/meg2'), ()),
            (('stat', '/rsrc'), ()),
            (('lstat', '/rsrc'), ()),
            (('stat', '/linksrc'), ()),
            (('lstat', '/linksrc'), ()),
            (('stat', '/linkdest'), ()),
            (('lstat', '/linkdest'), ()),
            (('stat', '/dir'), ()),
            (('lstat', '/dir'), ()),
            (('stat', '/dir/dir2'), ()),
            (('lstat', '/dir/dir2'), ()),
            (('stat', '/dir/nested'), ()),
            (('lstat', '/dir/nested'), ()),
    
            (('-v', 'stat', '/'), ()),
            (('-v', 'lstat', '/'), ()),
            (('-v', 'stat', '/meg1'), ()),
            (('-v', 'lstat', '/meg2'), ()),
            (('-v', 'stat', '/rsrc'), ()),
            (('-v', 'lstat', '/rsrc'), ()),
            (('-v', 'stat', '/linksrc'), ()),
            (('-v', 'lstat', '/linksrc'), ()),
            (('-v', 'stat', '/linkdest'), ()),
            (('-v', 'lstat', '/linkdest'), ()),
            (('-v', 'stat', '/dir'), ()),
            (('-v', 'lstat', '/dir'), ()),
            (('-v', 'stat', '/dir/dir2'), ()),
            (('-v', 'lstat', '/dir/dir2'), ()),
            (('-v', 'stat', '/dir/nested'), ()),
            (('-v', 'lstat', '/dir/nested'), ()),
    
            (('statfs', '/'), (fixStatFS,)),
            (('lstatfs', '/'), (fixStatFS,)),
            (('statfs', '/meg1'), (fixStatFS,)),
            (('lstatfs', '/meg1'), (fixStatFS,)),
    
            (('-v', 'statfs', '/'), (fixStatFS,)),
            (('-v', 'lstatfs', '/'), (fixStatFS,)),
            (('-v', 'statfs', '/meg1'), (fixStatFS,)),
            (('-v', 'lstatfs', '/meg1'), (fixStatFS,)),
        ]

    if fullDump:
        commands += [
            (('getdirentries', '/'), ()),
            (('getdirentries', '/dir'), ()),
            (('getdirentries', '/dir/dir2'), ()),
            (('getdirentries', '-bufSize', '10240', '/'), ()),
            (('getdirentries', '-r', '/'), ()),
    
            (('-v', 'getdirentries', '/'), ()),
            (('-v', 'getdirentries', '/dir'), ()),
            (('-v', 'getdirentries', '/dir/dir2'), ()),
            (('-v', 'getdirentries', '-bufSize', '10240', '/'), ()),
            (('-v', 'getdirentries', '-r', '/'), ()),
    
            (('readdir', '/'), ()),
            (('readdir', '/dir'), ()),
            (('readdir', '/dir/dir2'), ()),
            (('readdir', '-r', '/'), ()),
    
            (('-v', 'readdir', '/'), (fixTellDir,)),
            (('-v', 'readdir', '/dir'), (fixTellDir,)),
            (('-v', 'readdir', '/dir/dir2'), (fixTellDir,)),
            (('-v', 'readdir', '-r', '/'), (fixTellDir,)),
    
            (('fts', '/'), (fixFTSPointers,)),
            # fts has a bunch of options arguments but I can't be bothered exercising those cases.
        ]

    if fullDump:
        commands += [
            (('listxattr', '/meg1'), ()),
            (('listxattr', '/xattr'), ()),
            (('listxattr', '/rsrc'), ()),
            (('listxattr', '-bufSize', '10240', '/xattr'), ()),
    
            (('getxattr', '/xattr', 'com.apple.FinderInfo'), ()),
            (('getxattr', '/rsrc', 'com.apple.ResourceFork'), ()),
    
            (('-v', 'getxattr', '/xattr', 'com.apple.FinderInfo'), ()),
            (('-v', 'getxattr', '/rsrc', 'com.apple.ResourceFork'), ()),

            (('-vv', 'getxattr', '/xattr', 'com.apple.FinderInfo'), ()),
            (('-vv', 'getxattr', '/rsrc', 'com.apple.ResourceFork'), ()),
        ]

    # In the commented out cases below it seems to be that getattrlist is misbehaving. 
    # I seem to remember seeing this problem because but I don't have time to investigate 
    # right now.
    
    if fullDump:
        commands += [
            (('getattrlist', '/'), ()),
            (('getattrlist', '-ATTR_CMN_NAME', '/'), ()),
            (('getattrlist', '-ATTR_CMN_NAME', '/meg1'), ()),
            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/'), ()),
            (('getattrlist', '-ATTR_VOL_INFO,ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/'), ()),
            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/meg1'), ()),
            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/xattr'), ()),
            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID', '/'), ()),
            (('getattrlist', '-ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/'), ()),
            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
#            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
#            (('getattrlist', '-ATTR_VOL_INFO,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/'), ()),
            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/meg1'), ()),
#            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/meg1'), ()),
#            (('getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/meg1'), ()),
#            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
#            (('getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/meg1'), ()),

            (('-v', 'getattrlist', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME', '/meg1'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_VOL_INFO,ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/meg1'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/xattr'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
#            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
#            (('-v', 'getattrlist', '-ATTR_VOL_INFO,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/meg1'), ()),
#            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/meg1'), ()),
#            (('-v', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/meg1'), ()),
#            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
#            (('-v', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/meg1'), ()),

            (('-vv', 'getattrlist', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME', '/meg1'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_VOL_INFO,ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/meg1'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_CMN_FNDRINFO', '/xattr'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
#            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
#            (('-vv', 'getattrlist', '-ATTR_VOL_INFO,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_VOL_FSTYPE,ATTR_VOL_SIGNATURE,ATTR_VOL_SIZE,ATTR_VOL_SPACEFREE,ATTR_VOL_SPACEAVAIL,ATTR_VOL_MINALLOCATION,ATTR_VOL_ALLOCATIONCLUMP,ATTR_VOL_IOBLOCKSIZE,ATTR_VOL_OBJCOUNT,ATTR_VOL_FILECOUNT,ATTR_VOL_DIRCOUNT,ATTR_VOL_MAXOBJCOUNT,ATTR_VOL_MOUNTPOINT,ATTR_VOL_NAME,ATTR_VOL_MOUNTFLAGS,ATTR_VOL_MOUNTEDDEVICE,ATTR_VOL_ENCODINGSUSED,ATTR_VOL_CAPABILITIES,ATTR_VOL_ATTRIBUTES', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS', '/meg1'), ()),
#            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/meg1'), ()),
#            (('-vv', 'getattrlist', '-ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_CMN_NAME,ATTR_CMN_DEVID,ATTR_CMN_FSID,ATTR_CMN_OBJTYPE,ATTR_CMN_OBJTAG,ATTR_CMN_OBJID,ATTR_CMN_OBJPERMANENTID,ATTR_CMN_PAROBJID,ATTR_CMN_SCRIPT,ATTR_CMN_CRTIME,ATTR_CMN_MODTIME,ATTR_CMN_CHGTIME,ATTR_CMN_ACCTIME,ATTR_CMN_BKUPTIME,ATTR_CMN_FNDRINFO,ATTR_CMN_OWNERID,ATTR_CMN_GRPID,ATTR_CMN_ACCESSMASK,ATTR_CMN_FLAGS,ATTR_CMN_USERACCESS,ATTR_CMN_EXTENDED_SECURITY,ATTR_CMN_UUID,ATTR_CMN_GRPUUID,ATTR_CMN_FILEID,ATTR_CMN_PARENTID,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/meg1'), ()),
#            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/'), ()),
#            (('-vv', 'getattrlist', '-ATTR_CMN_OBJTYPE,ATTR_DIR_LINKCOUNT,ATTR_DIR_ENTRYCOUNT,ATTR_DIR_MOUNTSTATUS,ATTR_FILE_LINKCOUNT,ATTR_FILE_TOTALSIZE,ATTR_FILE_ALLOCSIZE,ATTR_FILE_IOBLOCKSIZE,ATTR_FILE_CLUMPSIZE,ATTR_FILE_DEVTYPE,ATTR_FILE_DATALENGTH,ATTR_FILE_DATAALLOCSIZE,ATTR_FILE_DATAEXTENTS,ATTR_FILE_RSRCLENGTH,ATTR_FILE_RSRCALLOCSIZE,ATTR_FILE_RSRCEXTENTS', '/meg1'), ()),
        ]

    if fullDump:
        commands += [
            (('FSGetVolumeInfo', '/'), (fixVolumeDates,)),

            (('-v', 'FSGetVolumeInfo', '/'), (fixVolumeDates,)),

            (('FSGetVolumeParms', '/'), (fixVolParmsPointers,)),
            (('-v', 'FSGetVolumeParms', '/'), (fixVolParmsPointers,)),
        ]

    if fullDump:
        commands += [
            (('FSGetCatalogInfo', '/'), ()),
            (('FSGetCatalogInfo', '/meg1'), ()),
            (('FSGetCatalogInfo', '/meg2'), ()),
            (('FSGetCatalogInfo', '/dir'), ()),
            (('FSGetCatalogInfo', '/acl'), ()),
            (('FSGetCatalogInfo', '/linksrc'), ()),
            (('FSGetCatalogInfo', '/linkdest'), ()),
            (('FSGetCatalogInfo', '/rsrc'), ()),
            (('FSGetCatalogInfo', '/xattr'), ()),

            (('FSGetCatalogInfo', '-parent', '/'), ()),
            (('FSGetCatalogInfo', '-parent', '/meg1'), ()),
            (('FSGetCatalogInfo', '-parent', '/meg2'), ()),
            (('FSGetCatalogInfo', '-parent', '/dir'), ()),
            (('FSGetCatalogInfo', '-parent', '/acl'), ()),
            (('FSGetCatalogInfo', '-parent', '/linksrc'), ()),
            (('FSGetCatalogInfo', '-parent', '/linkdest'), ()),
            (('FSGetCatalogInfo', '-parent', '/rsrc'), ()),
            (('FSGetCatalogInfo', '-parent', '/xattr'), ()),

            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/'), (fixCatInfoPermissions,)),
            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/meg1'), (fixCatInfoPermissions,)),
            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/meg2'), (fixCatInfoPermissions,)),
            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/dir'), (fixCatInfoPermissions,)),
            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/acl'), (fixCatInfoPermissions,)),
            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/linksrc'), (fixCatInfoPermissions,)),
            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/linkdest'), (fixCatInfoPermissions,)),
            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/rsrc'), (fixCatInfoPermissions,)),
            (('FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/xattr'), (fixCatInfoPermissions,)),

            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/'), ()),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/meg1'), ()),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/meg2'), ()),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/dir'), ()),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/acl'), ()),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/linksrc'), ()),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/linkdest'), ()),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/rsrc'), ()),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/xattr'), ()),

            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/'), ()),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/meg1'), ()),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/meg2'), ()),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/dir'), ()),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/acl'), ()),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/linksrc'), ()),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/linkdest'), ()),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/rsrc'), ()),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoGettableInfo', '/xattr'), ()),

            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/meg1'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/meg2'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/dir'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/acl'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/linksrc'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/linkdest'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/rsrc'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/xattr'), (fixCatInfoPermissions, fixFileSecOwner)),

            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/'), (fixFileSecOwner,)),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/meg1'), (fixFileSecOwner,)),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/meg2'), (fixFileSecOwner,)),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/dir'), (fixFileSecOwner,)),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/acl'), (fixFileSecOwner,)),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/linksrc'), (fixFileSecOwner,)),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/linkdest'), (fixFileSecOwner,)),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/rsrc'), (fixFileSecOwner,)),
            (('-v', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/xattr'), (fixFileSecOwner,)),

            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/'), (fixFileSecOwner,)),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/meg1'), (fixFileSecOwner,)),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/meg2'), (fixFileSecOwner,)),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/dir'), (fixFileSecOwner,)),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/acl'), (fixFileSecOwner,)),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/linksrc'), (fixFileSecOwner,)),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/linkdest'), (fixFileSecOwner,)),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/rsrc'), (fixFileSecOwner,)),
            (('-vv', 'FSGetCatalogInfo', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/xattr'), (fixFileSecOwner,)),
        ]

    if fullDump:
        commands += [
            (('FSGetCatalogInfoBulk', '/meg1'), ()),
            (('FSGetCatalogInfoBulk', '/dir'), ()),

            (('FSGetCatalogInfoBulk', '-refs', '/'), ()),
            (('FSGetCatalogInfoBulk', '-refs', '/dir'), ()),

            (('FSGetCatalogInfoBulk', '-count', '2', '/'), ()),
            (('FSGetCatalogInfoBulk', '-count', '2', '/dir'), ()),

            (('FSGetCatalogInfoBulk', '-kFSCatInfoGettableInfo', '/'), (fixCatInfoPermissions,)),
            (('FSGetCatalogInfoBulk', '-kFSCatInfoGettableInfo', '/dir'), (fixCatInfoPermissions,)),

            (('-v', 'FSGetCatalogInfoBulk', '-kFSCatInfoGettableInfo', '/'), (fixCatInfoPermissions,)),
            (('-v', 'FSGetCatalogInfoBulk', '-kFSCatInfoGettableInfo', '/dir'), (fixCatInfoPermissions,)),

            (('-vv', 'FSGetCatalogInfoBulk', '-kFSCatInfoGettableInfo', '/'), (fixCatInfoPermissions,)),
            (('-vv', 'FSGetCatalogInfoBulk', '-kFSCatInfoGettableInfo', '/dir'), (fixCatInfoPermissions,)),

            (('FSGetCatalogInfoBulk', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('FSGetCatalogInfoBulk', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/dir'), (fixCatInfoPermissions, fixFileSecOwner)),

            (('-v', 'FSGetCatalogInfoBulk', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('-v', 'FSGetCatalogInfoBulk', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/dir'), (fixCatInfoPermissions, fixFileSecOwner)),

            (('-vv', 'FSGetCatalogInfoBulk', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/'), (fixCatInfoPermissions, fixFileSecOwner)),
            (('-vv', 'FSGetCatalogInfoBulk', '-kFSCatInfoPermissions,kFSCatInfoFSFileSecurityRef', '/dir'), (fixCatInfoPermissions, fixFileSecOwner)),
        ]

    if fullDump:
        commands += [
            (('FSFindFolder', '/', 'asup'), ()),
        ]

    if fullDump:
        commands += [
            (('FSCopyAliasInfo', '/'), (fixAliasVolumeCreateDate,)),
            (('FSCopyAliasInfo', '/meg1'), (fixAliasVolumeCreateDate,)),
            (('FSCopyAliasInfo', '/xattr'), (fixAliasVolumeCreateDate,)),
        ]

    # There is no /dev/tty on the test volume.  Maybe I could put a symlink there? 
    # Right now that's too much work for the benefit that I'll get.
    
    if fullDump:
        commands += [
            (('pathconf', '_PC_LINK_MAX', '/'), ()),
#            (('pathconf', '_PC_MAX_CANON', '/dev/tty'), ()),
#            (('pathconf', '_PC_MAX_INPUT', '/dev/tty'), ()),
            (('pathconf', '_PC_NAME_MAX', '/'), ()),
            (('pathconf', '_PC_PATH_MAX', '/'), ()),
            (('pathconf', '_PC_PIPE_BUF', '/'), ()),
            (('pathconf', '_PC_CHOWN_RESTRICTED', '/'), ()),
            (('pathconf', '_PC_NO_TRUNC', '/'), ()),
#            (('pathconf', '_PC_VDISABLE', '/dev/tty'), ()),
            (('pathconf', '_PC_NAME_CHARS_MAX', '/'), ()),
            (('pathconf', '_PC_CASE_SENSITIVE', '/'), ()),
            (('pathconf', '_PC_CASE_PRESERVING', '/'), ()),
            (('pathconf', '_PC_EXTENDED_SECURITY_NP', '/'), ()),
            (('pathconf', '_PC_AUTH_OPAQUE_NP', '/'), ()),
            (('pathconf', '_PC_2_SYMLINKS', '/'), ()),
            (('pathconf', '_PC_ALLOC_SIZE_MIN', '/'), ()),
            (('pathconf', '_PC_ASYNC_IO', '/'), ()),
            (('pathconf', '_PC_FILESIZEBITS', '/'), ()),
            (('pathconf', '_PC_PRIO_IO', '/'), ()),
            (('pathconf', '_PC_REC_INCR_XFER_SIZE', '/'), ()),
            (('pathconf', '_PC_REC_MAX_XFER_SIZE', '/'), ()),
            (('pathconf', '_PC_REC_MIN_XFER_SIZE', '/'), ()),
            (('pathconf', '_PC_REC_XFER_ALIGN', '/'), ()),
            (('pathconf', '_PC_SYMLINK_MAX', '/'), ()),
            (('pathconf', '_PC_SYNC_IO', '/'), ()),
        ]
    
    print >> sys.stdout, "arch: %s" % arch
    print >> sys.stdout, "version: %s" % runTool(["sw_vers", "-productVersion"])[1].strip()
    print >> sys.stdout
    
    for command in commands:
        args = []
        for arg in command[0]:
            if arg[:1] == "/":
                args += [os.path.join(pathToTestVolume, arg[1:])]
            else:
                args += [arg]
        results = runFSMegaInfo(args, arch)
        for fix in command[1]:
            results = fix(results, arch)

        testStatus = results[0]
        testOutput = results[1]
        testError  = results[2]
        if testOutput == '':
            testOutput = []
        else:
            testOutput = testOutput.splitlines()
        if testError == '':
            testError = []
        else:
            testError = testError.splitlines()
        print >> sys.stdout, "args: %s" % str(command[0])
        print >> sys.stdout, "results: %d %d %d" % (testStatus, len(testOutput), len(testError))
        print >> sys.stdout, "---"
        for l in testOutput:
            print >> sys.stdout, l
        print >> sys.stdout, "---"
        for l in testError:
            print >> sys.stdout, l
        print >> sys.stdout, "---"
        sys.stdout.flush()

def printUsage():
    print >> sys.stderr, "usage: %s [ pathToTestVolume [ arch ] ]" % os.path.basename(sys.argv[0])

try:
    opts, args = getopt.getopt(sys.argv[1:], "d")
except getopt.GetoptError, e:
    printUsage()
    sys.exit(1)
    
for opt in opts:
    if opt[0] == "-d":
        gDebug += 1

gNativeArch = runTool(["arch"])[1].strip()

if len(args) == 0:
    runCrossArchitectureTest()
elif len(args) == 1:
    generateFingerPrint(args[0], "")
elif len(args) == 2:
    generateFingerPrint(args[0], arch)
else:
    printUsage()
    sys.exit(1)
