/*
     File: CompositeView.h
 Abstract: CompositeView implements a view with three horizontal, equal-sized areas.
 The left-most area is the "source," the middle area is the "destination,"
 and the right-most area is the "result." CompositeView assures that the
 contents of the result area is always generated by compositing the other
 two areas using the compositing mode set in the setOperator: method.
 It is also possible to change the contents, color, and alpha of the
 source and destination areas; see the methods setSourceColor:, 
 setSourceAlpha:, etc.
 
 CompositeView also demonstrates some of the drag and drop features
 by acting as a destination for colors and images.
  Version: 1.1
 
 Disclaimer: IMPORTANT:  This Apple software is supplied to you by Apple
 Inc. ("Apple") in consideration of your agreement to the following
 terms, and your use, installation, modification or redistribution of
 this Apple software constitutes acceptance of these terms.  If you do
 not agree with these terms, please do not use, install, modify or
 redistribute this Apple software.
 
 In consideration of your agreement to abide by the following terms, and
 subject to these terms, Apple grants you a personal, non-exclusive
 license, under Apple's copyrights in this original Apple software (the
 "Apple Software"), to use, reproduce, modify and redistribute the Apple
 Software, with or without modifications, in source and/or binary forms;
 provided that if you redistribute the Apple Software in its entirety and
 without modifications, you must retain this notice and the following
 text and disclaimers in all such redistributions of the Apple Software.
 Neither the name, trademarks, service marks or logos of Apple Inc. may
 be used to endorse or promote products derived from the Apple Software
 without specific prior written permission from Apple.  Except as
 expressly stated in this notice, no other rights or licenses, express or
 implied, are granted by Apple herein, including but not limited to any
 patent rights that may be infringed by your derivative works or by other
 works in which the Apple Software may be incorporated.
 
 The Apple Software is provided by Apple on an "AS IS" basis.  APPLE
 MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION
 THE IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS
 FOR A PARTICULAR PURPOSE, REGARDING THE APPLE SOFTWARE OR ITS USE AND
 OPERATION ALONE OR IN COMBINATION WITH YOUR PRODUCTS.
 
 IN NO EVENT SHALL APPLE BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL
 OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 INTERRUPTION) ARISING IN ANY WAY OUT OF THE USE, REPRODUCTION,
 MODIFICATION AND/OR DISTRIBUTION OF THE APPLE SOFTWARE, HOWEVER CAUSED
 AND WHETHER UNDER THEORY OF CONTRACT, TORT (INCLUDING NEGLIGENCE),
 STRICT LIABILITY OR OTHERWISE, EVEN IF APPLE HAS BEEN ADVISED OF THE
 POSSIBILITY OF SUCH DAMAGE.
 
 Copyright (C) 2011 Apple Inc. All Rights Reserved.
 
 */

#import <Cocoa/Cocoa.h>

// The possible draw modes for the source.

typedef enum {	// Various pictures that can be drawn in the source (or even destination) areas
  TrianglePicture = 0,
  CirclePicture,
  DiamondPicture,
  HeartPicture,
  FlowerPicture,
  CustomPicture
} CompositeViewPicture;

@interface CompositeView:NSView {
    id source, destination, result, customImage;
    NSRect sRect, dRect, rRect;
    NSCompositingOperation operator;
    CompositeViewPicture sourcePicture;
    NSColor *sourceColor, *destColor, *backgroundColor;

    // Outlets...
    id sourceColorWell;
    id destColorWell;
    id backColorWell;
    id sourcePictureMatrix;
}

// Init/dealloc
- (id)initWithFrame:(NSRect)rect;
- (void)dealloc;

// Target-action methods
- (void)setSourcePicture:(id)sender;
- (void)setOperator:(id)sender;
- (void)changeCustomImage:(id)sender;
- (void)changeSourceColor:(id)sender;
- (void)changeDestColor:(id)sender;
- (void)changeBackgroundColor:(id)sender;

// Outlet-setting methods (we need these to set the initial colors)
- (void)setSourceColorWell:(id)anObject;
- (void)setDestColorWell:(id)anObject;
- (void)setBackColorWell:(id)anObject;

// Methods to change the colors and display
- (void)changeSourceColorTo:(NSColor *)color andDisplay:(BOOL)flag;
- (void)changeDestColorTo:(NSColor *)color andDisplay:(BOOL)flag;
- (void)changeBackgroundColorTo:(NSColor *)color andDisplay:(BOOL)flag;
- (BOOL)changeCustomImageTo:(NSImage *)newImage;

// Callbacks from NSImage drawing methods
- (void)drawSource:(NSCustomImageRep *)imageRep;
- (void)drawDestination:(NSCustomImageRep *)imageRep;
- (void)drawResult:(NSCustomImageRep *)imageRep;

// Other methods
- (void)drawRect:(NSRect)rect;
- (NSCompositingOperation)operator;

// Dragging methods
- (NSUInteger)draggingEntered:(id <NSDraggingInfo>)sender;
- (NSUInteger)draggingUpdated:(id <NSDraggingInfo>)sender;
- (void)draggingExited:(id <NSDraggingInfo>)sender;
- (BOOL)performDragOperation:(id <NSDraggingInfo>)sender;
- (void)concludeDragOperation:(id <NSDraggingInfo>)sender;
- (void)doColorDrag:(id <NSDraggingInfo>)sender;

@end



